### ISSUE TITLE
Support building and running on AIX

### ISSUE THREAD

**Issue by hellerda** [open-power/sb-signing-utils#13]
Some users require support for sb-signing-utils on AIX.  We can use this Issue to track all the requirements for porting, i.e., any changes that need to made to the code, and use separate Issues to track the individual changes.

The first issue found is:
- Need replacement for getopt_long() on AIX (issue #14)

**Comment by mtvaught-ibm** [comment]
Second issue found:
- AIX doesn't support `date -d <>`, need a replacement (issue #15 )

**Comment by hellerda** [comment]
Third issue:

- Need replacement for 'xxd" (issue #20)

**Comment by hellerda** [comment]
Status:
- Issue 1: See my latest comments in Issue #14   Latest test patch in PR #21.
- Issue2: Resolved (PR #19), closed.  ./
- Issue3: Resolved (commit ids e34abf2 and 549bd6b), closed. /

**Comment by hellerda** [comment]
All issues now resolved and patches committed.  Closing this issue as complete.
